spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/testdbuniversity
    username: u
    password: 1
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka