server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: UNIVERSITY-SERVICE
  datasource:
    url: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${random.value}}

logging:
  level:
    root: info
    org.andarworld.courseservice: debug