spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/testdbuniversity
    username: u
    password: 1
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/realms/test_security_realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8888/realms/test_security_realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka